### ISSUE TITLE
You can't license this work under the GPL

### ISSUE THREAD

**Issue by jtgans** [c128lib/Reference#44]
Vast copies of the Cowper's Mapping the Commodore 128 is present this reference. That's straight up plagiarism, and it also can't be placed under the GPL because you don't own it... -_-

**Comment by intoinside** [comment]
For this Reference several sources were used, Mapping the Commodore 128 is the most relevant. I'm not an expert on licenses, in your opinion what could be the most suitable license or what activities can be done to avoid having problems?

**Comment by jtgans** [comment]
"Using" a source and writing your own words is one thing. Wholesale copying of paragraphs is quite another. You have to rewrite everything you copied in your own words and give bibliographic references.

Once that is done, you can license how you wish, but as it is, what you're doing is plaigarism and could be taken down. Worse, because of the license, it's being added to Copilot's training set. Set the license to proprietary first, maybe take down the reference for now, and rewrite what you copied.

**Comment by intoinside** [comment]
Thank you @jtgans, I deleted all the contents and now I will start from scratch reevaluating and rewriting where necessary. I'll start from memory map so we can also fix #43

**Comment by intoinside** [comment]
Closed, this is an extensive edit, it will be tracked differently
